FROM node:16.13.2

RUN mkdir -p /usr/src/client

WORKDIR /usr/src/client

ADD . /usr/src/client


EXPOSE 3000

COPY package.json ./
COPY ./src ./src
COPY ./public ./public

RUN npm install -g npm@8.4.1
RUN npm run build