FROM node:16.13.2 as build-step

RUN mkdir -p /usr/src/client

WORKDIR /usr/src/client

ADD . /usr/src/client


EXPOSE 3000

COPY package.json ./
COPY ./src ./src
COPY ./public ./public

RUN yarn install -g npm@8.4.1
RUN yarn run build


# Build step #2: build an nginx container
FROM nginx:stable-alpine
COPY --from=build-step /usr/src/client/build /usr/share/nginx/html
COPY deployment/nginx.default.conf /etc/nginx/conf.d/default.conf