version: "3.5"
services:
  client:
    container_name: fast-check-client
    build:
      context: ./client
      dockerfile: dockerfile.client
    image: fast-check-client
    volumes:
      - ./client:/frontend
    command: >
            npm start
    depends_on:
      - server
    ports:
      - "3000:3000"
  server:
    container_name: fast-check-api-no-dlib
    # restart: always
    build:
      context: ./server
      dockerfile: dockerfile.server
    environment:
      API_ENV: 'docker_prod'
    image: fast-check-api-no-dlib
    volumes:
      - ./server:/backend
    links:
      - mysql5_7
    ports:
      - "3001:3001"
    # command: python manage.py db upgrade
    command: >
      sh -c " 
      python manage.py run"
  mysql5_7:
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysql5_7:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_USER: 'root'
      MYSQL_DATABASE: 'fast_check_prod'
      # MYSQL_HOST: '0.0.0.0'
    ports:
      - "32000:3306"
