export const GET_ROOMS = "GET_ROOMS"
export const GET_ROOM_SUCCESS = "GET_ROOM_SUCCESS"
export const GET_ROOM_FAILED = "GET_ROOM_FAILED"


export const GETROOM = "GET_ROOM"
export const GETROOM_SUCCESS = "GET_ROOM_SUCCESS"
export const GETROOM_FAILED = "GET_ROOM_FAILED"


export const ADD_ROOM = "ADD_ROOM"
export const ADD_ROOM_SUCCESS = "ADD_ROOM_SUCCESS"
export const ADD_ROOM_FAILED = "ADD_ROOM_FAILED"


export const POST_ROOM = "POST_ROOM"
export const POST_ROOM_SUCCESS = "POST_ROOM_SUCCESS"
export const POST_ROOM_FAILED = "POST_ROOM_FAILED"


export const DELETE_ROOM = "DELETE_ROOM"
export const DELETE_ROOM_SUCCESS = "DELETE_ROOM_SUCCESS"
export const DELETE_ROOM_FAILED = "DELETE_ROOM_FAILED"