FROM python:3.7.11

EXPOSE 3001
WORKDIR /app
COPY requirements.txt /app
RUN pip install --upgrade pip
# RUN pip install cmake
RUN pip install -r requirements.txt
RUN apt-get update && apt-get install -y python3-opencv
COPY . .
# RUN apt-get install -y python3-opencv


RUN chmod u+x ./setup.sh
CMD ["./setup.sh"]
# ENTRYPOINT ["./usr/src/appentrypoint.sh"]
# RUN  python manage.py db upgrade