"""empty message

Revision ID: 0cdf1f9d4ffa
Revises: 36f8b761e512
Create Date: 2022-01-26 15:30:23.098052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0cdf1f9d4ffa'
down_revision = '36f8b761e512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('room',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('publicId', sa.String(length=150), nullable=True),
    sa.Column('roomName', sa.String(length=100), nullable=False),
    sa.Column('timeSchedule', sa.Text(), nullable=True),
    sa.Column('dateSchedule', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('participantNumber', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_history',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('roomId', sa.String(length=150), nullable=False),
    sa.Column('date', sa.Text(), nullable=True),
    sa.Column('timeStart', sa.Text(), nullable=True),
    sa.Column('timeEnd', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['roomId'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('roomId', sa.String(length=150), nullable=False),
    sa.Column('userId', sa.String(length=150), nullable=False),
    sa.Column('dateJoined', sa.Text(), nullable=False),
    sa.Column('isAdmin', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['roomId'], ['room.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_status',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('participantId', sa.String(length=150), nullable=False),
    sa.Column('attendanceHistoryId', sa.String(length=150), nullable=False),
    sa.Column('isPresent', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['attendanceHistoryId'], ['attendance_history.id'], ),
    sa.ForeignKeyConstraint(['participantId'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('hasAvatar', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'user', ['password_hash'])
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'hasAvatar')
    op.drop_table('attendance_status')
    op.drop_table('participants')
    op.drop_table('attendance_history')
    op.drop_table('room')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
