"""empty message

Revision ID: 1a2391ae8c4f
Revises: 2fcffb42fc68
Create Date: 2022-02-08 11:07:56.373913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2391ae8c4f'
down_revision = '2fcffb42fc68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_history',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('roomId', sa.String(length=150), nullable=False),
    sa.Column('date', sa.Text(), nullable=True),
    sa.Column('timeStart', sa.Text(), nullable=True),
    sa.Column('timeEnd', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['roomId'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_status',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('userId', sa.String(length=150), nullable=False),
    sa.Column('attendanceHistoryId', sa.String(length=150), nullable=False),
    sa.Column('isPresent', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['attendanceHistoryId'], ['attendance_history.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance_status')
    op.drop_table('attendance_history')
    # ### end Alembic commands ###
