"""fix: change from auto incre to uuid4

Revision ID: 23f7e64b029a
Revises: 80b1f97a3fa8
Create Date: 2021-09-22 16:12:46.986705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f7e64b029a'
down_revision = '80b1f97a3fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('publicId', sa.String(length=150), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dateDelta', sa.Text(), nullable=True),
    sa.Column('timeEnd', sa.Text(), nullable=True),
    sa.Column('timeStart', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=150), nullable=False),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password_hash')
    )
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roomId', sa.String(length=150), nullable=False),
    sa.Column('userId', sa.String(length=150), nullable=False),
    sa.Column('dateJoined', sa.Text(), nullable=False),
    sa.Column('idAdmin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['roomId'], ['room.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participants')
    op.drop_table('user')
    op.drop_table('room')
    # ### end Alembic commands ###
