"""refact: change publib_id to publicId

Revision ID: 28f965d50c25
Revises: 6443321318e4
Create Date: 2021-09-22 10:08:14.674593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f965d50c25'
down_revision = '6443321318e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('publicId', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'publicId')
    # ### end Alembic commands ###
