"""empty message

Revision ID: 2c515d87d2cf
Revises: a4fa2390e024
Create Date: 2021-11-08 10:40:00.130995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c515d87d2cf'
down_revision = 'a4fa2390e024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendanceHistory',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('roomId', sa.String(length=150), nullable=False),
    sa.Column('date', sa.Text(), nullable=True),
    sa.Column('timeStart', sa.Text(), nullable=True),
    sa.Column('timeEnd', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['roomId'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendanceStatus',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('participantId', sa.String(length=150), nullable=False),
    sa.Column('attendanceHistoryId', sa.String(length=150), nullable=False),
    sa.Column('isPresent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['attendanceHistoryId'], ['attendanceHistory.id'], ),
    sa.ForeignKeyConstraint(['participantId'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('attendancehistory')
    op.drop_table('attendance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('participantId', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('dateCheckAttendance', mysql.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['participantId'], ['participants.id'], name='attendance_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('attendancehistory',
    sa.Column('id', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('roomId', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('date', mysql.TEXT(), nullable=True),
    sa.Column('timeStart', mysql.TEXT(), nullable=True),
    sa.Column('timeEnd', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['roomId'], ['room.id'], name='attendancehistory_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('attendanceStatus')
    op.drop_table('attendanceHistory')
    # ### end Alembic commands ###
