"""empty message

Revision ID: 2fcffb42fc68
Revises: c8ea834fa5c4
Create Date: 2022-02-07 15:23:01.816330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2fcffb42fc68'
down_revision = 'c8ea834fa5c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_status', sa.Column('userId', sa.String(length=150), nullable=False))
    op.drop_constraint('attendance_status_ibfk_2', 'attendance_status', type_='foreignkey')
    op.create_foreign_key(None, 'attendance_status', 'user', ['userId'], ['id'])
    op.drop_column('attendance_status', 'participantId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_status', sa.Column('participantId', mysql.VARCHAR(length=150), nullable=False))
    op.drop_constraint(None, 'attendance_status', type_='foreignkey')
    op.create_foreign_key('attendance_status_ibfk_2', 'attendance_status', 'participants', ['participantId'], ['id'])
    op.drop_column('attendance_status', 'userId')
    # ### end Alembic commands ###
