"""fix: simplify room model

Revision ID: 56f31f9f9dbf
Revises: ddda9d35362b
Create Date: 2021-10-18 21:48:11.996890

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '56f31f9f9dbf'
down_revision = 'ddda9d35362b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('dateSchedule', sa.Text(), nullable=True))
    op.add_column('room', sa.Column('timeSchedule', sa.Text(), nullable=True))
    op.drop_column('room', 'timeEnd')
    op.drop_column('room', 'timeStart')
    op.drop_column('room', 'dateDelta')
    op.drop_column('room', 'dateStart')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('dateStart', mysql.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('room', sa.Column('dateDelta', mysql.TEXT(), nullable=True))
    op.add_column('room', sa.Column('timeStart', mysql.TEXT(), nullable=True))
    op.add_column('room', sa.Column('timeEnd', mysql.TEXT(), nullable=True))
    op.drop_column('room', 'timeSchedule')
    op.drop_column('room', 'dateSchedule')
    # ### end Alembic commands ###
