"""empty message

Revision ID: 7bb230f4e30f
Revises: 7668a46dc75a
Create Date: 2021-09-21 16:05:24.201627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7bb230f4e30f'
down_revision = '7668a46dc75a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('password_hash', table_name='user')
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', mysql.VARCHAR(length=10), nullable=False))
    op.create_index('password_hash', 'user', ['password_hash'], unique=True)
    # ### end Alembic commands ###
