"""empty message

Revision ID: 8092623f16ba
Revises: 9267699be496
Create Date: 2021-11-06 14:57:42.470212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8092623f16ba'
down_revision = '9267699be496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('participantId', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('dateCheckAttendance', mysql.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['participantId'], ['participants.id'], name='attendance_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
