"""empty message

Revision ID: 889bac133028
Revises: 9c46ae751385
Create Date: 2021-09-21 15:31:43.313920

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '889bac133028'
down_revision = '9c46ae751385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'avatar',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'avatar',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
