"""empty message

Revision ID: 9267699be496
Revises: 56f31f9f9dbf
Create Date: 2021-11-06 14:40:28.333643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9267699be496'
down_revision = '56f31f9f9dbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('participantId', sa.String(length=150), nullable=False),
    sa.Column('dateCheckAttendance', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['participantId'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    # ### end Alembic commands ###
