"""empty message

Revision ID: a4fa2390e024
Revises: 8092623f16ba
Create Date: 2021-11-07 21:53:43.513583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4fa2390e024'
down_revision = '8092623f16ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendanceHistory',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('roomId', sa.String(length=150), nullable=False),
    sa.Column('date', sa.Text(), nullable=True),
    sa.Column('timeStart', sa.Text(), nullable=True),
    sa.Column('timeEnd', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['roomId'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendanceHistory')
    # ### end Alembic commands ###
