"""empty message

Revision ID: bac01c44e850
Revises: 0cdf1f9d4ffa
Create Date: 2022-01-26 15:42:23.855663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bac01c44e850'
down_revision = '0cdf1f9d4ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('room',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('publicId', sa.String(length=150), nullable=True),
    sa.Column('roomName', sa.String(length=100), nullable=False),
    sa.Column('timeSchedule', sa.Text(), nullable=True),
    sa.Column('dateSchedule', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('participantNumber', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=150), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('hasAvatar', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('attendance_history',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('roomId', sa.String(length=150), nullable=False),
    sa.Column('date', sa.Text(), nullable=True),
    sa.Column('timeStart', sa.Text(), nullable=True),
    sa.Column('timeEnd', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['roomId'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('roomId', sa.String(length=150), nullable=False),
    sa.Column('userId', sa.String(length=150), nullable=False),
    sa.Column('dateJoined', sa.Text(), nullable=False),
    sa.Column('isAdmin', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['roomId'], ['room.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance_status',
    sa.Column('id', sa.String(length=150), nullable=False),
    sa.Column('participantId', sa.String(length=150), nullable=False),
    sa.Column('attendanceHistoryId', sa.String(length=150), nullable=False),
    sa.Column('isPresent', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['attendanceHistoryId'], ['attendance_history.id'], ),
    sa.ForeignKeyConstraint(['participantId'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance_status')
    op.drop_table('participants')
    op.drop_table('attendance_history')
    op.drop_table('user')
    op.drop_table('room')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
