"""empty message

Revision ID: c66cc8215bc0
Revises: 7bb230f4e30f
Create Date: 2021-09-21 16:05:38.379337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c66cc8215bc0'
down_revision = '7bb230f4e30f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=1000), nullable=False))
    op.create_unique_constraint(None, 'user', ['password_hash'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
