"""rename to participantNumber

Revision ID: ddda9d35362b
Revises: f08e75154a51
Create Date: 2021-10-06 15:43:09.081452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ddda9d35362b'
down_revision = 'f08e75154a51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('participantNumber', sa.Integer(), nullable=True))
    op.drop_column('room', 'numOfStudent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('numOfStudent', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('room', 'participantNumber')
    # ### end Alembic commands ###
