"""feat: Auth and Participants

Revision ID: e9067210678e
Revises: 4401b7e2330e
Create Date: 2021-09-22 09:38:23.844720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9067210678e'
down_revision = '4401b7e2330e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.add_column('participants', sa.Column('roomId', sa.Integer(), nullable=False))
    op.drop_constraint('participants_ibfk_1', 'participants', type_='foreignkey')
    op.create_foreign_key(None, 'participants', 'room', ['roomId'], ['id'])
    op.drop_column('participants', 'roomID')
    op.add_column('room', sa.Column('public_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['password_hash'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('room', 'public_id')
    op.add_column('participants', sa.Column('roomID', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'participants', type_='foreignkey')
    op.create_foreign_key('participants_ibfk_1', 'participants', 'room', ['roomID'], ['id'])
    op.drop_column('participants', 'roomId')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
