"""empty message

Revision ID: eafa1d603e85
Revises: bac01c44e850
Create Date: 2022-01-26 15:42:52.834518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eafa1d603e85'
down_revision = 'bac01c44e850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.Text(), nullable=False))
    op.create_unique_constraint(None, 'user', ['password_hash'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
