"""empty message

Revision ID: eec2201f1ce4
Revises: 1a2391ae8c4f
Create Date: 2022-02-19 09:53:14.964578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec2201f1ce4'
down_revision = '1a2391ae8c4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_status', sa.Column('CheckedTime', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance_status', 'CheckedTime')
    # ### end Alembic commands ###
